version: 2
root-markers:
  - .git/

tools:
  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort --stdout -'
    format-stdin: true

  python-autopep8: &python-autopep8
    format-command: 'autopep8 -'
    format-stdin: true
  
  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  cppcheck-lint: &cppcheck-lint
    prefix: cppcheck
    lint-command: 'cppcheck --quiet --std --force --enable=style --error-exitcode=1 ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: %m'
    root-markers:
    - compile_commands.json


languages:
  python:
    - <<: *python-black
    - <<: *python-autopep8
    - <<: *python-isort
    - <<: *python-flake8
  
  cpp:
    - <<: *cppcheck-lint

  c:
    - <<: *cppcheck-lint
