cursor #e2e3e1
cursor_text_color #c0c8c5

foreground            #e2e3e1
background            #121413
selection_foreground  #243330
selection_background  #b9cac5
url_color             #a4cfc4

color0   #121413
color1   #ee966b
color2   #67cf6d
color3   #fff372
color4   #93c4b8
color5   #3b5f56
color6   #a4cfc4
color7   #ccd9d6
color8   #7c8684
color9   #ffbe9f
color10  #a1f8a6
color11  #fff7a5
color12  #bbe3d9
color13  #d9fff5
color14  #e7fff8
color15  #f8fffd
