cursor #e3e2e9
cursor_text_color #c5c6d0

foreground            #e3e2e9
background            #121318
selection_foreground  #2a3042
selection_background  #c1c6dd
url_color             #b3c5ff

color0   #121318
color1   #ff7298
color2   #7fff93
color3   #fff872
color4   #9bb0f2
color5   #354476
color6   #b3c5ff
color7   #eff3ff
color8   #999ca5
color9   #ff9fb9
color10  #a5ffb3
color11  #fffba5
color12  #becdff
color13  #c9d6ff
color14  #dce4ff
color15  #f8faff
