cursor #e4e2e5
cursor_text_color #c6c6ce

foreground            #e4e2e5
background            #131316
selection_foreground  #2c303d
selection_background  #c2c6d7
url_color             #bac6ed

color0   #131316
color1   #ff7298
color2   #76ed89
color3   #fff872
color4   #a7b4e1
color5   #424c6d
color6   #bac6ed
color7   #e9edf8
color8   #8e919a
color9   #ff9fb9
color10  #a5ffb3
color11  #fffba5
color12  #d0dbff
color13  #d8e1ff
color14  #e6ecff
color15  #f8faff
